### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/Overlord-Project#40]
# Overview 
An Example issue to show how to correctly use the DevOps pipeline.

## Intended Outcome
Help team understand the pipeline and use it correctly, speeding up our process and reducing errors

## Tasks
- [ ] Create Issue
- [ ] Add Issue as Project's Card
- [ ] Create branch to solve issue
- [ ] Commit and Pull Request
- [ ] Check CI automatic verification
- [ ] Wait for Review, correct problems and PR until done
- [ ] Close Issue
