### ISSUE TITLE
Integrar Gerador de NPCs com a Develop

### ISSUE THREAD

**Issue by ga-hirakawa** [LeonardoTPereira/Overlord-Project#52]
# Overview 
O código do Gerador de NPCs está atualmente desacoplado, isolado do projeto principal.

# # Intended outcome
Deixar o gerador integrado e funcional com o projeto.

# # Tasks
- [x] Fazer branch da dev?
- [x] Incluir script EnumJobs
- [x] Incluir script EnumRaces
- [x] Incluir script Evolutivo
- [x] incluir script CSVManager
- [x] Incluir script Gerador NPCs
- [x] Incluir script MapElites
- [x] Incluir script FitnessScript
- [x] Incluir o Scriptable Object NPC_SO
- [ ] Tirar dúvidas

# # Dúvidas
Unificar o código também inclui conectar as funções que criamos com o gerador dos outros? (gerador de quests, mapa mundo, etc)?
Não tá aparecendo a opção de Overlord na aba de projetos aqui do lado (>>>). Não estamos conseguindo atribuir tarefa por causa disso.
